//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDT {
    
    
    public partial class AltaEntrenamientoWF {
        
        /// <summary>
        /// AltaEntrenamiento_ComboEquipo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AltaEntrenamiento_ComboEquipo;
        
        /// <summary>
        /// AltaEntrenamiento_ComboLugar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AltaEntrenamiento_ComboLugar;
        
        /// <summary>
        /// AltaEntrenamiento_ComboActividad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AltaEntrenamiento_ComboActividad;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SEDT.SiteMaster Master {
            get {
                return ((SEDT.SiteMaster)(base.Master));
            }
        }
    }
}
